development:
  adapter: postgresql
  encoding: unicode
  database: pocket_lint_development
  host: localhost
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pocket_lint_test
  host: localhost
  pool: 5
  username: postgres
  password:
